### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by samagra14** [YoungXIAO13/FewShotViewpoint#4]
Hi @YoungXIAO13 

I have been trying to run the demo script and I am getting the following error. Can you help out here? I am somewhat inexperienced with pytorch.

````
Traceback (most recent call last):
  File "demo.py", line 79, in <module>
    out = model(im, None, mean_class_data=cls_data)
  File "/home/samagra14/miniconda3/envs/FSviewpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/samagra14/6d_pose/FewShotViewpoint/auxiliary/model.py", line 103, in forward
    img_feature = self.img_encoder(im)  # B*C
  File "/home/samagra14/miniconda3/envs/FSviewpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "./auxiliary/resnet.py", line 137, in forward
    x = self.conv1(x)
  File "/home/samagra14/miniconda3/envs/FSviewpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/samagra14/miniconda3/envs/FSviewpoint/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
````

Thanks

**Comment by YoungXIAO13** [comment]
Hi @samagra14 

I found some related discussion: [here](https://discuss.pytorch.org/t/cuda-error-runtimeerror-cudnn-status-execution-failed/17625) and [here](https://github.com/pytorch/pytorch/issues/32921)

This errors seems also strange to me, according to [one of the answers](https://github.com/pytorch/pytorch/issues/32921#issuecomment-581734069): you can try sth like ```CUDA_LAUNCH_BLOCKING=1 python demo.py```.

And it could also rise from the mismatched version of PyTorch and CUDA.

Otherwise you can try using it on CPU to bypass the usage of CUDA.
